DROP DATABASE IF EXISTS DICTIONARY_DB;

CREATE DATABASE DICTIONARY_DB;

USE DICTIONARY_DB;

CREATE TABLE DICTIONARY(
	ID INTEGER(10) AUTO_INCREMENT NOT NULL,
    WORD VARCHAR(100) NOT NULL,
    MEANING VARCHAR(1000),
    PRIMARY KEY(ID)
);