DROP DATABASE IF EXISTS efBayDB;

CREATE DATABASE efBayDB;

USE efBayDB;

CREATE TABLE items (
  id INT NOT NULL AUTO_INCREMENT,
  item VARCHAR(45) NULL,
  category VARCHAR(45) NULL,
  bid DECIMAL(10,2) NULL,
  PRIMARY KEY (id)
);
